# Generated by Django 5.2.4 on 2025-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_options_rename_massege_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login_reqire',
            field=models.BooleanField(default=False),
        ),
    ]
